import csv
import io
import os

class TemporalCsvPublisher:
    """
    A temporary stateful CSV publisher designed specifically for the Dashboard Testing project.
    It reads the output generated by the Factory and merges it with the historical CSV on disk.
    
    Rules:
    - PAST dates (< record_date): Locked to whatever was in the old CSV file (or blanked if no file).
    - TODAY (== record_date): Overwritten with the fresh live metrics from the Factory.
    - FUTURE dates (> record_date): Metrics blanked out (0), but Burndown forecasts preserved.
    """
    @staticmethod
    def publish(csv_content: str, record_date: str, output_path: str):
        # 1. Read existing CSV if it exists
        historical_rows = {}
        if os.path.exists(output_path):
            try:
                with open(output_path, "r", encoding="utf-8") as f:
                    reader = csv.reader(f)
                    _ = next(reader, None)  # Skip header
                    for row in reader:
                        if row and len(row) > 0:
                            historical_rows[row[0]] = row
            except Exception:
                pass # If it's corrupted or locked, we just proceed as if it's new

        # 2. Parse the freshly computed CSV content from the Factory
        new_reader = csv.reader(io.StringIO(csv_content))
        headers = next(new_reader, [])
        
        output = io.StringIO(newline="")
        writer = csv.writer(output)
        writer.writerow(headers)
        
        # Determine where the Left Side (Daily Metrics) and Right Side (Sprint Timeline) split
        # We look for the double empty string separator ["", ""] in the header
        gap_idx = 33  # Hardcoded fallback
        for i in range(len(headers) - 1):
            if headers[i] == "" and headers[i+1] == "" and len(headers) > i+2 and headers[i+2] != "":
                gap_idx = i
                break

        for row in new_reader:
            if not row:
                continue
            
            row_date = row[0]
            
            # Safely slice the row
            left_side = row[:gap_idx]
            separator = row[gap_idx:gap_idx+2] if len(row) >= gap_idx+2 else ["", ""]
            right_side = row[gap_idx+2:] if len(row) > gap_idx+2 else []
            
            final_left = left_side.copy()
            
            # --- Temporal Merge Logic ---
            if row_date < record_date:
                if row_date in historical_rows:
                    # We have a historical record for this date! Lock it in.
                    old_row = historical_rows[row_date]
                    final_left = old_row[:gap_idx]
                else:
                    # No history exists for this past date (e.g. brand new project).
                    # Blank out all actual metrics (indices 2 through 29)
                    for i in range(2, min(30, len(final_left))):
                        final_left[i] = ""
                    # Blank out SPDelta
                    if len(final_left) > 32:
                        final_left[32] = ""
                        
            elif row_date > record_date:
                # The future hasn't happened yet. Blank out the actuals!
                for i in range(2, min(30, len(final_left))):
                    final_left[i] = ""
                # Blank out SPDelta
                if len(final_left) > 32:
                    final_left[32] = ""
                    
            else:
                # TODAY (row_date == record_date)
                # Keep final_left exactly as generated by the Factory (writing today's hard truth)
                pass
                
            writer.writerow(final_left + separator + right_side)
            
        # 3. Save to disk
        with open(output_path, "w", encoding="utf-8", newline="") as f:
            f.write(output.getvalue())
